name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: website
          git-user: github-actions
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages