name: CI
on: [push]

jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: website
          git-user: github-actions
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
